# Generated by Django 3.0.4 on 2020-11-17 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Triagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='* Campos obrigatórios', max_length=20, unique=True, verbose_name='Código da triagem *')),
                ('data', models.DateField(help_text='dd/mm/aaaa', max_length=11, verbose_name='Data da triagem *')),
                ('hora', models.CharField(help_text='hh:mm', max_length=5, verbose_name='Hora da triagem *')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do paciente *')),
                ('idade', models.IntegerField(verbose_name='Idade do paciente *')),
                ('altura', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Altura do paciente *')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Peso do paciente *')),
                ('imc', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='IMC do paciente *')),
                ('q1', models.BooleanField(verbose_name='Tem febre? *')),
                ('q2', models.BooleanField(verbose_name='Tem dor de cabeça? *')),
                ('q3', models.BooleanField(verbose_name='Tem secreção nasal ou espirros? *')),
                ('q4', models.BooleanField(verbose_name='Tem dor/irritação na garganta? *')),
                ('q5', models.BooleanField(verbose_name='Tem tosse seca? *')),
                ('q6', models.BooleanField(verbose_name='Tem dificuldade respiratória? *')),
                ('q7', models.BooleanField(verbose_name='Tem dores no corpo? *')),
                ('q8', models.BooleanField(verbose_name='Tem diarréia? *')),
                ('q9', models.BooleanField(verbose_name='Viajou nos últimos 14 dias para local com casos confirmados de COVID-19? *')),
                ('q10', models.BooleanField(verbose_name='Esteve em contato, nos últimos 14 dias com um caso diagnosticado de COVID-19? *')),
                ('risco', models.IntegerField(verbose_name='Risco do paciente *')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
                ('atendente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atendente', to=settings.AUTH_USER_MODEL, verbose_name='Atendente *')),
            ],
            options={
                'verbose_name': 'triagem',
                'verbose_name_plural': 'triagens',
                'ordering': ['-data', '-hora'],
                'unique_together': {('codigo', 'data', 'hora')},
            },
        ),
    ]
